version: '3.8'

services:
  master01: &default-instance
    build:
      context: .
      dockerfile: Dockerfile
    container_name: master
    networks:
      os-network:
    privileged: true
    environment:
      TZ: "Asia/Ho_Chi_Minh"

  slave01: 
    <<: *default-instance
    container_name: slave01

  slave02:
    <<: *default-instance
    container_name: slave02

  slave03:
    <<: *default-instance
    container_name: slave03

networks:
  os-network:
